Repository fpmi-tp2022/CycJluku, pull requests merged in 2022-04, with the labels that each got.

#39 feat: fill db
  doc/air_cab.db
Labels: attention!

#37 Draft: add default readme info
  .gitignore
  README.md
  doc/OPT.txt
  include/OPT.h
Labels: easy one

#41 feat: #20 select_1
  bin/OPT
  src/server.c
Labels: easy one, do it!

#42 feat: #21 select 2
  obj/opt
  src/server.c
Labels: attention!, do it!

#47 feat: solve #31
  doc/air_cab.db
  src/server.c
Labels: easy one

#48 feat: solve #32
  src/server.c
Labels: attention!, do it!

#49 feat: #33
  src/server.c
Labels: enhancement

#51 Develop
  .github/workflows/build.yml
  .gitignore
  Makefile
  README.md
  doc/air_cab.db
  doc/air_cab_db_create.sql
  example
  include/server.h
  include/variables.h
  obj/opt
  src/main.c
  src/server.c
Labels: documentation, enhancement, alert!, attention!, do it!, to finish!
